---
- name: update apt
  apt: >
    update_cache=yes
    cache_valid_time=3600
  when: ansible_os_family == "Debian"

- name: install deps (Ubuntu)
  apt: 
    name: ["python-pip", "python-dev"]
    state: present
  when: ansible_os_family == "Debian"

- name: install deps (RHEL)
  yum:
    name: ["python-pip", "python-devel"]
    state: installed
  when: ansible_os_family == "RedHat"

- name: install python module consulate
  pip:
    name: ["tornado", "consulate"]
